cancer = read.csv("/Users/pooja.vasudevan/Downloads/cancerdata.csv")
summary(cancer)
str(cancer)
#Data Wrangling
cancer$target[cancer$Classification==2]=1
cancer$target[cancer$Classification==1]=0
View(cancer)
mod <- glm(formula=target ~ Age+BMI+Glucose, family=binomial, data=cancer)
summary(mod)
library(caTools)
set.seed(88)
split = sample.split(cancer$target, SplitRatio = 0.75)
cancerTrain = subset(cancer, split==TRUE)
cancerTest = subset(cancer, split==FALSE)
CancerLog = glm(target ~ Age + BMI, family=binomial, data=cancerTrain)
summary(CancerLog)
predictTrain = predict(CancerLog, type="response")
summary(predictTrain)
tapply(predictTrain, cancerTrain$target, mean)
table(cancerTrain$target, predictTrain > 0.5)
plot(mod)
mod.res=resid(mod)
plot(cancer$BMI, mod.res, ylab="Residuals", xlab="BMI", main="BMI Factors")
ROCRpred = prediction(predictTrain, cancerTrain$target)
ROCRpref = performance(ROCRpred, "tpr", "fpr")
plot(ROCRpref, colorize=TRUE)
